### ISSUE TITLE
Issues from the old repo

### ISSUE THREAD

**Issue by Zren** [Zren/plasma-applet-eventcalendar#2]
* [x] [Not syncing new/modified events](https://github.com/Zren/plasma-applets/issues/126)
* [ ] [Crash in latte dock](https://github.com/Zren/plasma-applets/issues/121)
* [ ] [Memory leak when update events](https://github.com/Zren/plasma-applets/issues/118)
* [ ] [Thin vertical transparent bar at right edge of calendar](https://github.com/Zren/plasma-applets/issues/115)
* [x] [Expand list of calendars in add-popup](https://github.com/Zren/plasma-applets/pull/107)
* [x] [Event notification sound](https://github.com/Zren/plasma-applets/issues/105)
* [ ] [google calendar data will be abandoned when run kde on a no network environment](https://github.com/Zren/plasma-applets/issues/103)
* [x] [Google Calendar shows nothing and refuses to logout](https://github.com/Zren/plasma-applets/issues/101)
* [ ] [Multiple (Google) accounts to sync calendar](https://github.com/Zren/plasma-applets/issues/96)
* [x] [Feature request](https://github.com/Zren/plasma-applets/issues/94)
* [ ] [Custom timer lengths](https://github.com/Zren/plasma-applets/issues/93)
* [x] [plasmashell crashes with gcal enabled](https://github.com/Zren/plasma-applets/issues/92)
* [ ] [Error loading QML file](https://github.com/Zren/plasma-applets/issues/90)
* [x] [Highlight color should be selectable](https://github.com/Zren/plasma-applets/issues/80)
* [ ] [Quick Add places events on current date instead of target date (when gcal language is "ru"/Русский)](https://github.com/Zren/plasma-applets/issues/76)
* [x] [Google Calendar error](https://github.com/Zren/plasma-applets/issues/74)
* [x] [Option to Disable Shadow in Panel](https://github.com/Zren/plasma-applets/issues/72)
* [x] [Overlapping TImer and Agenda, when Meteogram Hidden](https://github.com/Zren/plasma-applets/issues/71)
* [x] [Event Calendar doesn't use the right scaling](https://github.com/Zren/plasma-applets/issues/66)
* [x] [How can I move the days column?](https://github.com/Zren/plasma-applets/issues/63)
* [ ] [Allow changing order of date format](https://github.com/Zren/plasma-applets/issues/61)
* [ ] [Event Calendar causes plasmashell crash if an event summary contains emojis](https://github.com/Zren/plasma-applets/issues/60)
* [x] [DPI Scaling](https://github.com/Zren/plasma-applets/pull/58)
* [ ] [.ics Sync (aka iCalendar, ical, CalDAV) (Local or Remote)](https://github.com/Zren/plasma-applets/issues/57)
* [ ] [Nothing in the Google Callendar Settings](https://github.com/Zren/plasma-applets/issues/56)
* [x] [A request for showing time from another timezone in the mouse over popup (tool tip) on the event calendar widget](https://github.com/Zren/plasma-applets/issues/49)
* [ ] [Show agenda under month](https://github.com/Zren/plasma-applets/issues/47)
* [ ] [Event Notifications](https://github.com/Zren/plasma-applets/issues/46)
* [ ] [Clock isn't usuable when used as a desktop widget](https://github.com/Zren/plasma-applets/issues/44)
* [x] [Callendars not configurable (selectable and Collors) anymore](https://github.com/Zren/plasma-applets/issues/43)
* [x] [Wether not working anymore](https://github.com/Zren/plasma-applets/issues/42)
* [x] [event callendar Date will not advance](https://github.com/Zren/plasma-applets/issues/41)
* [ ] [Repeat timer sfx __ times (or loop until notification dismiss if possible)](https://github.com/Zren/plasma-applets/issues/40)
* [ ] [Weather Underground](https://github.com/Zren/plasma-applets/issues/39)
* [x] [Improve weather configuration by pointing out full city list](https://github.com/Zren/plasma-applets/issues/31)
* [x] [Toggling Compositor (Shift+Alt+F12) breaks checkboxes in the Timer](https://github.com/Zren/plasma-applets/issues/28)
* [x] [hide calendar & add automatic updates patches](https://github.com/Zren/plasma-applets/pull/27)
* [x] [Pin option](https://github.com/Zren/plasma-applets/issues/26)
* [x] [today events highlighted](https://github.com/Zren/plasma-applets/issues/25)
* [x] [Support for Dark themes](https://github.com/Zren/plasma-applets/pull/24)
* [x] [Timer notification sound](https://github.com/Zren/plasma-applets/issues/23)
* [x] [Repeated event](https://github.com/Zren/plasma-applets/issues/22)
* [x] [Fahrenheit](https://github.com/Zren/plasma-applets/issues/20)
* [ ] [Week Numbers in agenda](https://github.com/Zren/plasma-applets/issues/19)
* [x] [Timestamps are not formatted with 24h clock in the calendar + meteogram](https://github.com/Zren/plasma-applets/issues/18)
* [x] [MultiDay Events show up multiple times a day, and are formatted as "All Day" in the Agenda](https://github.com/Zren/plasma-applets/issues/17)
* [ ] [Make event color in agenda optionally use foreground color](https://github.com/Zren/plasma-applets/issues/16)
* [x] [Pin to stop hiding the calendar](https://github.com/Zren/plasma-applets/issues/15)
* [x] [Duplicate events when using wholeday feature](https://github.com/Zren/plasma-applets/issues/14)
* [x] [Plasmashell chashes (when using Qt 5.6)](https://github.com/Zren/plasma-applets/issues/13)
* [ ] [Akonadi / KDE Calendar Plugins Sync](https://github.com/Zren/plasma-applets/issues/12)
* [x] [Desktop Widget Support](https://github.com/Zren/plasma-applets/issues/11)
* [ ] [Task List](https://github.com/Zren/plasma-applets/issues/10)
* [x] [Config > Google Calendar](https://github.com/Zren/plasma-applets/issues/9)
* [x] [Meteogram](https://github.com/Zren/plasma-applets/issues/8)
* [x] [Show events every day for multi day events](https://github.com/Zren/plasma-applets/issues/7)
* [x] [time font size on vertical panel too large](https://github.com/Zren/plasma-applets/issues/6)
* [x] [crashes with plasma 5.6 / Qt 5.6](https://github.com/Zren/plasma-applets/issues/5)
* [ ] [Weather Icon / Current Temp in Panel](https://github.com/Zren/plasma-applets/issues/4)
* [x] [Provide ability to customise display](https://github.com/Zren/plasma-applets/issues/3)
* [x] [Wasted space / different colour on popup](https://github.com/Zren/plasma-applets/issues/2)
* [x] [Provide option to disable timer](https://github.com/Zren/plasma-applets/issues/1)

### Translations

* [French](https://github.com/Zren/plasma-applets/pull/129) [2nd translator](https://github.com/Zren/plasma-applets/issues/70)
* [German](https://github.com/Zren/plasma-applets/pull/79) 
* [Portegeuse Brazil](https://github.com/Zren/plasma-applets/issues/109)
* [Spanish](https://github.com/Zren/plasma-applets/pull/89)
* [Ukrainian](https://github.com/Zren/plasma-applets/issues/104)

**Comment by matty-r** [comment]
@Zren can tick "Akonadi / KDE Calendar Plugins Sync", as that issue is closed.

**Comment by PePoDev** [comment]
Any plan on this [`Multiple (Google) accounts to sync calendar`](https://github.com/Zren/plasma-applets/issues/96)?
